<html>
    <header><title>Dashboard</title>
    <h1>Dashboard</h1>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/contactus.css" type="text/css">
    <script src="https://kit.fontawesome.com/4b60169630.js" crossorigin="anonymous"></script>
    <nav>
        <ul>
            <li>Orders</li>
            <li>Order history</li>
            <li>Users</li>
            <li>Add product</li>
            <li>report</li>
        </ul>
    </nav>
</header>
<body>

</body>