
<?php require_once('template/header.phtml'); ?>

        <link rel="stylesheet" type="text/css" href="../css/blog.css">


    <div class="post">
        <h2>The Jolly Journal</h2>
        <p>Hey there, folks! We’ve got some exciting news for you! This blog page isn’t just a boring
            page about us. It’s a hangout, where we will keep you in the loop about our brand-new personalities
            and all details about what’s trending and famous in the world! But hold up, it’s not just about us,
            it’s also about you too! We want to know what you think about our charming and not so charming characters,</p>
    </div>

    <div class="post">

        <h2>Nutty</h2>
        <p>Nutty as a squirrel, who has a fondness for shiny objects. One day, he found a diamond
            ring and put it on his paw, unaware that it was enchanted. He looked like a blinged out superstar
            for sure, he eventually found himself performing wild aerobatics, juggling nuts, and tap dancing.
            Nutty learned a valuable lesson: sometimes, the pursuit of shiny things can lead to the most unexpected and
            hilarious adventures. The end.</p>
    </div>

    <div class="post">

        <h2>ANANASS !</h2>
        <p>
            Ananass, a pineapple with a flair for the dramatic, yearned for adventure. Escape from the supermarket
            led him to Midnight, a streetwise cat. Together, they sang, danced, and chased city lights. Finally, Ananass
            found his paradise on a sun-drenched beach, his voice and spiky crown forever etched in local legend.</p>
    </div>

    <div class="post">

        <h2> Croissant</h2>
        <p>
            Croissant, a bakery escapee, hitched a ride on a balloon, soaring over the city. Landing in a park, he met
            Pip, a book-loving squirrel. Together, dodging pigeons and bargaining with vendors, they returned Croissant
            to the bakery, his heart full of adventure and a new friend.</p>
    </div>





    
    