<?php
?>
<script src="https://kit.fontawesome.com/39355bfe1f.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="/css/contactus.css"  type="text/css">

<div class="contact">
    <div class="content">
        <h2> Contact Us </h2>
        <p> We would love to hear from you at Aaseer!<br> Aaseer is all about creating
            a fun and pleasurable experience for our valued customers. If you have any
            questions, feedback, or simply want to say hello, our contact page is the perfect
            place to reach out. Our dedicated team is here to assist you and ensure your satisfaction.
             we're just a message or phone call away. We value your input and look forward to connecting
            with you. Get in touch with us today and let us bring a smile to your face with our refreshing juices
            and exceptional customer service.</p>
    </div>
    <div class="container1">
        <div class="contactInfo">
            <div class="box">
                <div class="icon"><i class="fa-solid fa-location-dot"></i></div>
                  <div class="text">
                     <h3> Address</h3>
                      <p> The station - Janabiah <br> Janabiah, highway 10 <br> kingdom of  bahrain  </p>
                  </div>
            </div>

            <div class="box">
                <div class="icon"><i class="fa-solid fa-phone"></i></div>
                    <div class="text">
                        <h3>Phone</h3>
                        <p>+973 33333333</p>
                    </div>

            </div>

            <div class="box">
                <div class="icon"><i class="fa-solid fa-envelope"></i></div>
                    <div class="text">
                        <h3>Email</h3>
                        <p>aaseer.sik@gmail.com</p>
                    </div>

            </div>
        </div>
        <div class="contactForm">
            <form action="https://formsubmit.co/a1db3e40f7352e6fa5eb1057174d327d" method="POST" />
        <//form onsubmit="sendEmail(); reset(); return false ">
<//form action="contactus.php" method="post">
                <h2> Send Message</h2>
                <div class="inputBox">
                    <input type="text" name="fullName" required="required">
                    <span>Full Name</span>
                </div>


                <div class="inputBox">
                    <input type="text" name="subject" required="required">
                    <span>Subject</span>
                </div>

                <div class="inputBox">
                    <input type="text" name="email" required="required">
                    <span>Email</span>
                </div>

                <div class="inputBox">
                    <textarea name="message" required="required"></textarea>
                    <span>type your message....</span>
                </div>
                <div class="inputBox">
                <input type="submit" name="submit" value="submit">
                </div>
            </form>
        </div>
    </div>
</div>
<div class="foot1">
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus eligendi 
        ratione nisi obcaecati excepturi architecto, earum in cupiditate perferendis molestias 
        quod ipsum sunt dicta veritatis, quas dolorem non adipisci. Dolore.</p>
</div>