<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link href="../Views/menu.js">
    <style>
        body {
            background-color: #f8f9fa;
            padding: 20px;
        }

        form {
            max-width: 400px;
            margin: 0 auto;
            background-color: #ffffff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            text-align: center;
            color: #007bff;
        }

        .form-group {
            margin-bottom: 20px;
        }

        label {
            font-weight: bold;
        }

        .btn-primary {
            width: 100%;
        }
    </style>
    <title>Menu Form</title>
</head>
<body>
<form action="../create.php" method="post" enctype="multipart/form-data">

    <h1>Adding new items to the menu</h1>
    <div class="form-group">
        <label for="photo">Upload Photo:</label>
        <input type="file" class="form-control-file" name="photo" accept="image/*">
    </div>

    <div class="form-group">
        <label for="juiceName">Juice Name:</label>
        <input type="text" class="form-control" name="juiceName" required>
    </div>

    <div class="form-group">
        <label for="description">Description:</label>
        <input type="text" class="form-control" name="description" required>
    </div>

    <label for="size">Size:</label>
    <select class="form-select" name="size" aria-label="Default select example">
        <option value="S">S</option>
        <option value="M">M</option>
        <option value="L">L</option>
    </select>

    <label for="price">Price:</label>
    <select class="form-select" name="price" aria-label="Default select example">
        <option value="1.15">1.15</option>
        <option value="1.25">1.25</option>
        <option value="1.45">1.45</option>
    </select>

    <div class="form-group">
        <label for="availability">Availability:</label>
        <input type="text" class="form-control" name="availability" required>
    </div>

    <button type="submit" name="submit" class="btn btn-primary">Submit</button>
</form>
</body>
</html>
