<!DOCTYPE html>
<html lang="en">
<head>
<link rel="stylesheet" href="../css/logIn.css">
    <script src="https://kit.fontawesome.com/39355bfe1f.js" crossorigin="anonymous"></script>
    <script
  src="https://code.jquery.com/jquery-3.7.1.min.js"
  integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
  crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>


    <meta charset="utf-8">
    <title>log in</title>

</head>
<body>
<div class="wrapper">
        <form class="login-form" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
        <h1>LOGIN</h1>

            <div class="input-box">
            <input type="email" id="email" name="email" placeholder="email" required >
                <i class="fa-solid fa-envelope"></i>

            </div>
            <div class="input-box">
              
            <input type="password" id="password" name="password" placeholder="password" required>
                <i class="fa-solid fa-lock"></i>

                </div>
               
            <button type="submit" name="submit" class="btn">LOGIN</button>
            <p class="signup-link">Don't have an account? <a href="../signUp.php">Sign up</a></p>
           <!--- <p class="signup-link" ><a href="../forgetPass.php">Forgot your password?</a></p> --->

        </form>
</div>
</body>
</html>