
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Loyalty Points - Aseer</title>
    <link rel="stylesheet" href="css/loyalityPoints.css" type="text/css">
</head>
<body>

  <main class="loyalty-points-container">
    <section class="loyalty-points">
      <h1> Total points</h1>
        <h2> 250 </h2>
      <p>Thank you for being a loyal customer!</p>

    </section>
  </main>

</body>
</html>
