<?php
?>

<link rel="stylesheet" href="../css/placedOrder.css">
<body>
<div class="container">
    <div class="pineapple">
        <div class="leaf"></div>
        <div class="leg-left"></div>
        <div class="leg-right"></div>
        <div class="eye-left"></div>
        <div class="eye-right"></div>
        <div class="mouth"></div>
    </div>
    <div class="shadow"></div>
</div>

<div class="pickup">
    <h2> thank you!</h2>
    <h4> your order has been placed successfully</h4>
<p>your order is being prepared , it will be ready within 15 minutes</p>
    <p> Upon picking up your order, please finalize the payment </p>
</div>
</body>