<?php
if(isset($_SESSION['email'])){
    require_once('Models/UserDataSet.php');
    $userDataSet = new UserDataSet();
       $userData = $userDataSet->fetchUserInfoByUser($_SESSION['email']);
       //print_r($userData);
       
   

}


?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CodingDung | Profile Template</title>
    <link rel="stylesheet" href="profile.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
<div class="container light-style flex-grow-1 container-p-y">
    <h4 class="font-weight-bold py-3 mb-4">
        Account settings
    </h4>
    <div class="card overflow-hidden">
        <div class="row no-gutters row-bordered row-border-light">
            <div class="col-md-3 pt-0">
                <div class="list-group list-group-flush account-settings-links">
                <a class="list-group-item list-group-item-action" 
                       href="../index.php">HOME</a>
                <a class="list-group-item list-group-item-action active" data-toggle="list"
                       href="#account-general">GENERAL</a>
                     
                       <a class="list-group-item list-group-item-action" 
                       href="../orderNow.php">ORDER NOW</a>
                    <a class="list-group-item list-group-item-action" data-toggle="list"
                       href="#account-social-links">FAQ's</a>
                    <a class="list-group-item list-group-item-action" data-toggle="list"
                       href="../logout.php">LOGOUT</a>
                    <a class="list-group-item list-group-item-action" data-toggle="list"
                       href="#account-notifications"></a>
                </div>
            </div>
            <div class="col-md-9">
                <div class="tab-content">
                    <div class="tab-pane fade active show" id="account-general">
                        <div class="card-body media align-items-center">
                            <img src="../img/user.png" alt width="18%" height="18%"
                                 class="d-block ui-w-80">
                            
                        </div>
                        <hr class="border-light m-0">
                        <div class="card-body">
                            <div class="form-group">
                                <label class="form-label">First Name</label>
                                <input type="text" class="form-control" disabled value="<?php echo $userData->getFirstName();?>">
                            </div>
                            <div class="form-group">
                                <label class="form-label">Last Name</label>
                                <input type="text" class="form-control" disabled value="<?php echo $userData->getLastName();?>">
                            </div>
                            <div class="form-group">
                                <label class="form-label">E-mail</label>
                                <input type="text" class="form-control mb-1" disabled value="<?php echo $userData->getEmail();?>">
                               
                            </div>
                            
                        </div>
                    </div>
                    <div class="tab-pane fade" id="account-change-password">
                        <div class="card-body pb-2">
                            <div class="form-group">
                                <label class="form-label">Current password</label>
                                <input type="password" class="form-control">
                            </div>
                            <div class="form-group">
                                <label class="form-label">New password</label>
                                <input type="password" class="form-control">
                            </div>
                            <div class="form-group">
                                <label class="form-label">Repeat new password</label>
                                <input type="password" class="form-control">
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="account-info">
                        <div class="card-body pb-2">
                            <div class="form-group">
                                <label class="form-label">Bio</label>
                                <textarea class="form-control"
                                          rows="5">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris nunc arcu, dignissim sit amet sollicitudin iaculis, vehicula id urna. Sed luctus urna nunc. Donec fermentum, magna sit amet rutrum pretium, turpis dolor molestie diam, ut lacinia diam risus eleifend sapien. Curabitur ac nibh nulla. Maecenas nec augue placerat, viverra tellus non, pulvinar risus.</textarea>
                            </div>
                            <div class="form-group">
                                <label class="form-label">Birthday</label>
                                <input type="text" class="form-control" value="May 3, 1995">
                            </div>
                            <div class="form-group">
                                <label class="form-label">Country</label>
                                <select class="custom-select">
                                    <option>USA</option>
                                    <option selected>Canada</option>
                                    <option>UK</option>
                                    <option>Germany</option>
                                    <option>France</option>
                                </select>
                            </div>
                        </div>
                        <hr class="border-light m-0">
                        <div class="card-body pb-2">
                            <h6 class="mb-4">Contacts</h6>
                            <div class="form-group">
                                <label class="form-label">Phone</label>
                                <input type="text" class="form-control" value="+0 (123) 456 7891">
                            </div>
                            <div class="form-group">
                                <label class="form-label">Website</label>
                                <input type="text" class="form-control" value>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="account-social-links">
                        <section>
                            <div class="container">
                                <div class="accordion">
                                    <div class="accordion-item" id="question1">
                                        <a class="accordion-link" href="#question1">
                                        How does the reward system work?

                                            <ion-icon class=" add-outline" name="add-outline"></ion-icon>
                                            <ion-icon class="remove-outline" name="remove-outline"></ion-icon>
                                        </a>
                                        <div class="answer">
                                            <p>You gain points by buying juices</p>
                                        </div>
                                    </div>
                                    <div class="accordion-item" id="question2">
                                        <a class="accordion-link" href="#question2">
                                        Where is your location?

                                            <ion-icon class=" add-outline" name="add-outline"></ion-icon>
                                            <ion-icon class="remove-outline" name="remove-outline"></ion-icon>
                                        </a>
                                        <div class="answer">
                                          <p>  We are located at the station Janabiya
</p>
                                        </div>
                                    </div>
                                    <div class="accordion-item" id="question3">
                                        <a class="accordion-link" href="#question3">
                                        Is your juice considered healthy?

                                            <ion-icon class=" add-outline" name="add-outline"></ion-icon>
                                            <ion-icon class="remove-outline" name="remove-outline"></ion-icon>
                                        </a>
                                        <div class="answer">
                                            <p>Yes our juices are considered healthy but are not low in calories 
</p>
                                        </div>
                                    </div>
                                    <div class="accordion-item" id="question4">
                                        <a class="accordion-link" href="#question4">
                                        What is your best seller 

                                            <ion-icon class=" add-outline" name="add-outline"></ion-icon>
                                            <ion-icon class="remove-outline" name="remove-outline"></ion-icon>
                                        </a>
                                        <div class="answer">
                                            <p>Our Dana juice seems to be the crowd’s favorite </p>
                                        </div>
                                    </div>
                                    <div class="accordion-item" id="question5">
                                        <a class="accordion-link" href="#question5">
                                        What time do you open

                                            <ion-icon class=" add-outline" name="add-outline"></ion-icon>
                                            <ion-icon class="remove-outline" name="remove-outline"></ion-icon>
                                        </a>
                                        <div class="answer">
                                            <p>We are open from 4pm to 2am</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
                    <div class="tab-pane fade" id="account-connections">
                        <div class="card-body">
                            <button type="button" class="btn btn-twitter">
                                <strong></strong></button>
                        </div>
                        <hr class="border-light m-0">
                        <div class="card-body">
                            <h5 class="mb-2">
                                <a href="javascript:void(0)" class="float-right text-muted text-tiny"><i
                                        class="ion ion-md-close"></i> </a>
                                <i class="ion ion-logo-google text-google"></i>

                            </h5>
                   <p></p>
                        </div>
                        <hr class="border-light m-0">
                        <div class="card-body">
                            <button type="button" class="btn btn-facebook">
                                <strong></strong></button>
                        </div>
                        <hr class="border-light m-0">
                        <div class="card-body">
                            <button type="button" class="btn btn-instagram">
                                <strong></strong></button>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="account-notifications">
                        <div class="card-body pb-2">
                            <h6 class="mb-4">Activity</h6>
                            <div class="form-group">
                                <label class="switcher">
                                    <input type="checkbox" class="switcher-input" checked>
                                    <span class="switcher-indicator">
                                            <span class="switcher-yes"></span>
                                            <span class="switcher-no"></span>
                                        </span>
                                    <span class="switcher-label">Email me when someone comments on my article</span>
                                </label>
                            </div>
                            <div class="form-group">
                                <label class="switcher">
                                    <input type="checkbox" class="switcher-input" checked>
                                    <span class="switcher-indicator">
                                            <span class="switcher-yes"></span>
                                            <span class="switcher-no"></span>
                                        </span>
                                    <span class="switcher-label">Email me when someone answers on my forum
                                            thread</span>
                                </label>
                            </div>
                            <div class="form-group">
                                <label class="switcher">
                                    <input type="checkbox" class="switcher-input">
                                    <span class="switcher-indicator">
                                            <span class="switcher-yes"></span>
                                            <span class="switcher-no"></span>
                                        </span>
                                    <span class="switcher-label">Email me when someone follows me</span>
                                </label>
                            </div>
                        </div>
                        <hr class="border-light m-0">
                        <div class="card-body pb-2">
                            <h6 class="mb-4">Application</h6>
                            <div class="form-group">
                                <label class="switcher">
                                    <input type="checkbox" class="switcher-input" checked>
                                    <span class="switcher-indicator">
                                            <span class="switcher-yes"></span>
                                            <span class="switcher-no"></span>
                                        </span>
                                    <span class="switcher-label">News and announcements</span>
                                </label>
                            </div>
                            <div class="form-group">
                                <label class="switcher">
                                    <input type="checkbox" class="switcher-input">
                                    <span class="switcher-indicator">
                                            <span class="switcher-yes"></span>
                                            <span class="switcher-no"></span>
                                        </span>
                                    <span class="switcher-label">Weekly product updates</span>
                                </label>
                            </div>
                            <div class="form-group">
                                <label class="switcher">
                                    <input type="checkbox" class="switcher-input" checked>
                                    <span class="switcher-indicator">
                                            <span class="switcher-yes"></span>
                                            <span class="switcher-no"></span>
                                        </span>
                                    <span class="switcher-label">Weekly blog digest</span>
                                </label>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


   
</div>

<script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript">

</script>
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
</body>

</html>