<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign Up - AASEER</title>
    <link rel="stylesheet" href="../css/signUp.css" type="text/css">
    <script src="https://kit.fontawesome.com/39355bfe1f.js" crossorigin="anonymous"></script>

</head>
<body>
<div class="container" >
    <div class="wrapper">
        <?php /* if ($view->createFlag== 1) { ?>
            <div style="margin-top:10px"><span style="color:white;border:5px; padding:7px;font-size: 14px;background: #28a745">
            Congratulations! You are successfully registered</span>
            </div>
        <?php } else if ($view->createFlag==2) { ?>
            <div><span style="color:white;font-size: 14px;background: #28a745">
            Error! Please try again or contact system administrator.</span>
            </div>
        <?php } */ ?>
        <h1>SIGN UP</h1>
        <form class="signup-form" method="post" action="signUp.php">
                <div class="input-box">
                <input type="text" id="firstname" name="firstname"  placeholder="First Name" required>
                <i class="fa-solid fa-user"></i>
                </div>
                <div class="input-box">
                    <input type="text" id="lastname" name="lastname"  placeholder="Last Name" required>
                    <i class="fa-solid fa-user"></i>
                </div>
                <div class="input-box">
                    <input type="email" id="email" name="email"  placeholder="email" required>
                    <i class="fa-solid fa-envelope"></i>
                </div>
                <div class="input-box">

                    <input type="password" id="password" name="password" placeholder="password" required>
                    <i class="fa-solid fa-lock"></i>
                </div>

            <button class="btn" type="submit" id="submit" name="submit">SIGNUP</button>
            </form>
            <p class="login-link">Already have an account? <a href="logIn.php">Log in</a></p>
    </div>
</div>
</body>
</html>