</div>
  <link rel="stylesheet" href="css/footer.css">
  <script src="https://kit.fontawesome.com/39355bfe1f.js" crossorigin="anonymous"></script>
<footer>
   <div class="waves">
       <div class="wave" id="wave1"></div>
       <div class="wave" id="wave2"></div>
       <div class="wave" id="wave3"></div>
       <div class="wave" id="wave4"></div>
       <div class="wave" id="wave5"></div>
   </div>
<ul class="social-icon">
<li><a href="#"><i class="fa-brands fa-instagram"></i></a></li>
<li><a href="#"><i class="fa-brands fa-x-twitter"></i></a></li>
<li><a href="#"><i class="fa-brands fa-tiktok"></i></a></li>
<li><a href="#"><i class="fa-brands fa-whatsapp"></i></a></li>
</ul>

<ul class="menu">
  <li><a href="index.php">Home</a></li>
  <li><a href="menu.php">Menu</a></li>
  <li><a href="orderNow.php">Order Now</a></li>
  <li><a href="blog.php">Blog</a></li>
  <li><a href="contactus.php">Contact us</a></li>
  <li><a href="profile.php">Profile</a></li>
  <li><a href="q&a.php">FAQ</a></li>
</ul>

<p>2023 Aaseer | All Rights Reserved SIK Group</p>

</footer>
</body>
</html>
