<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="with-device-width, initial-scale=1">
    <link rel="stylesheet" href="../../css/header.css"  type="text/css">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>responsive</title>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
</head>
<body>
<header class="header">
<a href="https://ibb.co/Rb6JDt3"><img src="https://i.ibb.co/nm1KL47/aaseer.png" alt="aaseer" border="0" height="60px" width="120px"></a>
<input type="checkbox" id="check">
    <label for="check" class="icons">
        <i class='bx bx-menu' id="menu-icon"></i>
        <i class='bx bx-x' id="close-icon"></i>
    </label>
    <nav class="navbar">
        <a href="../../index.php" style="--i:0;">HOME</a>
        <a href="../../newOrder.php" style="--i:3;">PLACE NEW ORDER</a>
        <a href="../../blog.php" style="--i:4;">BLOG</a>
        <a href="../../contactus.php" style="--i:4;">CONTACT US</a>
        <a href="../../q&a.php" style="--i:4;">FAQ</a>

    </nav>
</header>
</body>
</html>



